EndProject.MVC/Controllers/ChangePasswordController.cs
using EndProject.MVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace EndProject.MVC.Controllers
{
    public class ChangePasswordController : Controller
    {
        public IActionResult Index()
        {
            var token = HttpContext.Session.GetString("JWToken");
            var userId = HttpContext.Request.Cookies["UserId"];
            if (string.IsNullOrEmpty(token))
            {
                return RedirectToAction("Login", "User");
            }
            ChangePasswordViewModel changePasswordViewModel = new ChangePasswordViewModel();
            changePasswordViewModel.UserId = userId;
            changePasswordViewModel.Token = token;
            return View(changePasswordViewModel);
        }
    }
}

EndProject.MVC/Controllers/UserInformationController.cs
using EndProject.MVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace EndProject.MVC.Controllers;

public class UserInformationController : Controller
{
    Uri baseAddress = new Uri("https://localhost:7032/api");
    private readonly HttpClient _httpClient;
    public UserInformationController(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }
    public async Task<IActionResult> Index()
    {
        var token = HttpContext.Session.GetString("JWToken");
        var userId = HttpContext.Request.Cookies["UserId"];
        if (string.IsNullOrEmpty(token))
        {
            return RedirectToAction("Login", "User");
        }


        var response = await _httpClient.GetAsync(baseAddress + "/UserProfile/UserAboutGet/" + userId);
        var json1 = await response.Content.ReadAsStringAsync();
        var userInfo = JsonConvert.DeserializeObject<UserProfileViewModel>(json1);

        UserProfileViewModel viewModel = new UserProfileViewModel()
        {
            Token = token,
            UserAboutId = userInfo.UserAboutId,
            UserId = userInfo.UserId,
            UserName = userInfo.UserName,
            FirstName = userInfo.FirstName,
            LastName = userInfo.LastName,
            Gender = userInfo.Gender,
            Bio = userInfo.Bio,
            Country = userInfo.Country,
            City = userInfo.City,
            ProfileImageUrl = userInfo.ProfileImageUrl,
            BackgroundImageUrl = userInfo.BackgroundImageUrl
        };
        return View(viewModel);
    }
}

EndProject.MVC/Views/UserSettings/Index.cshtml
@{
    ViewData["Title"] = "User Settings";
}

<div class="middle-sidebar-bottom">
    <div class="middle-sidebar-left">
        <div class="middle-wrap">
            <div class="card w-100 border-0 bg-white shadow-xs p-0 mb-4">

                <div class="card-body p-lg-5 p-4 w-100 border-0">
                    <div class="row">
                        <div class="col-lg-12">
                            <h4 class="mb-4 font-xxl fw-700 mont-font mb-lg-5 mb-4 font-md-xs">Settings</h4>
                            <div class="nav-caption fw-600 font-xssss text-grey-500 mb-2">Genaral</div>
                            <ul class="list-inline mb-4">
                                <li class="list-inline-item d-block border-bottom me-0"><a asp-action="Index" asp-controller="UserInformation" class="pt-2 pb-2 d-flex align-items-center"><i class="btn-round-md bg-primary-gradiant text-white feather-home font-md me-3"></i> <h4 class="fw-600 font-xsss mb-0 mt-0">Acount Information</h4><i class="ti-angle-right font-xsss text-grey-500 ms-auto mt-3"></i></a></li>
                                <li class="list-inline-item d-block border-bottom me-0"><a href="default-notification.html" class="pt-2 pb-2 d-flex align-items-center"><i class="btn-round-md bg-gold-gradiant text-white feather-bell font-md me-3"></i> <h4 class="fw-600 font-xsss mb-0 mt-0">Notification</h4><i class="ti-angle-right font-xsss text-grey-500 ms-auto mt-3"></i></a></li>
                                <li class="list-inline-item d-block  me-0"><a asp-action="Index" asp-controller="ChangePassword" class="pt-2 pb-2 d-flex align-items-center"><i class="btn-round-md bg-blue-gradiant text-white feather-inbox font-md me-3"></i> <h4 class="fw-600 font-xsss mb-0 mt-0">Password</h4><i class="ti-angle-right font-xsss text-grey-500 ms-auto mt-3"></i></a></li>
                            </ul>

                            <div class="nav-caption fw-600 font-xsss text-grey-500 mb-2">Other</div>
                            <ul class="list-inline">
                                <li class="list-inline-item d-block border-bottom me-0"><a href="help-box.html" class="pt-2 pb-2 d-flex align-items-center"><i class="btn-round-md bg-primary-gradiant text-white feather-help-circle font-md me-3"></i> <h4 class="fw-600 font-xsss mb-0 mt-0">Help</h4><i class="ti-angle-right font-xsss text-grey-500 ms-auto mt-3"></i></a></li>
                                <li class="list-inline-item d-block me-0"><a id="LogOutBtn" class="pt-2 pb-2 d-flex align-items-center"><i class="btn-round-md bg-red-gradiant text-white feather-lock font-md me-3"></i> <h4 class="fw-600 font-xsss mb-0 mt-0">Logout</h4><i class="ti-angle-right font-xsss text-grey-500 ms-auto mt-3"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>